## CI workflow on Github action
name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'clusters/**' # Avoid running the CI on loops when Flux updates the cluster configs
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Install dependencies
        run: npm install
      - name: Start the application
        run: npm start &
      - name: Run API tests
        run: npm run test:api
      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: result.html
          path: result.html
      - name: Upload test results XML
        uses: actions/upload-artifact@v4
        with:
          name: results.xml
          path: results.xml

  build-and-push:
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timestamp
        id: timestamp
        run: echo "ts=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Extract metadata (tags, labels) for App
        id: meta-app
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/task-manager
          tags: |
            type=raw,value=ts-${{ steps.timestamp.outputs.ts }}
            type=sha
            type=raw,value=latest

      - name: Build and push App image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./_infra/Dockerfile
          push: true
          tags: ${{ steps.meta-app.outputs.tags }}
          labels: ${{ steps.meta-app.outputs.labels }}

      - name: Extract metadata (tags, labels) for Test Runner
        id: meta-test
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/task-manager-api-test
          tags: |
            type=raw,value=ts-${{ steps.timestamp.outputs.ts }}
            type=sha
            type=raw,value=latest

      - name: Build and push Test Runner image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./_infra/api-test.dockerfile
          push: true
          tags: ${{ steps.meta-test.outputs.tags }}
          labels: ${{ steps.meta-test.outputs.labels }}
